### ISSUE TITLE
API proposal

### ISSUE THREAD

**Issue by stoeffel** [fp-dom/fd-class#2]
This is a API proposal for addClass, but the basic idea can be applied to other functions too.
Two points are important:
- most functions take functions as arguments
- most functions return curryied functions.
# addClass

``` js
// addClass(getClass:Function(index:Int) --> String, getElements:Function() --> Array);

var setDisabled = addClass(always('disabled'));

setDisabled(query('.item'));

var alternate = addClass(function(index) {
  return (index % 2 === 0)?'even' : 'odd';
});

alternate(query('li'));
```

**Comment by hemanth** [comment]
`query` if normal DOM query it would return a `NodeList` not an `Array`, should we implement `DOMQuery` first?

**Comment by stoeffel** [comment]
> query if normal DOM query it would return a NodeList not an Array, should we implement DOMQuery first?

agreed
